=pod

=head0 Route Handlers

=begin epigraph

TODO

=end epigraph

Route handlers are the core of a Dancer application. They can be as simple as a
static mapping and as complex as a pure Perl regular expression.

In this chapter we'll cover all the details about route handlers and we'll see
how to organize them when your application grows.

L<methods>
L<patterns>
L<regex>
L<prefix>
L<control_flow>

=head1 Conclusion

TODO

=cut
