=pod

=head0 Preface

=begin epigraph

"Without deviation from the norm, progress is not possible."

- Frank Zappa

=end epigraph

PerlDancer is a library used for web development since 2009 and became quickly a
popular choice for Perl developers wanting to write web applications.

It has a striving community and is still heavily used and developed more than
four years after its first release.

This book attempts to give a full overview over Dancer's philosophy, features,
and ecosystem. 

I hope you'll enjoy reading this book as much as you could enjoy writing a web
application with Dancer, and I hope that it will become your companion when 
tackling a web development project.

Let's enter the dance floor!

=head1 Origins

L<CGI>
L<MVC>
L<microframework>
L<DSL>
L<PSGI>
L<versions>

=head1 Credits

This book would not have been possible without the help of many people.

While the author tried very hard to fix all typos and errors in this book,
imperfections might still exist, and are the fault of the imperfect author. 

=cut
