=pod

=head0 First Moves

=begin epigraph

"One's destination is never a place, but a new way of seeing things."

- Henry Miller

=end epigraph

In this chapter we'll setup our working environment, we'll get to know Dancer's 
basics and we'll write our first web application with it.

L<working_environment>
L<HTTP>
L<minimal_application>

=head1 Conclusion

We've seen in this chapter how we could create a Dancer application from
scratch, starting with a dummy I<Hello World> thing to a (still dummy) more
complex application with templates, static files and configuration bits.

Of course, Dancer is much, much more than the top of the iceberg we've just
seen, but I hope this chapter helped to give you an idea of how things are done
with it.

We'll now continue our journey to better and more fun web development with a
chapter focused on the power of route handlers. Get ready for heavy dispatching.

=cut
